## MAIN VARS ##
# audio_dir :       "/media/vincent/Extreme SSD/MA/20221019-Benoit/transfer_1780104_files_cfc5b86f/SABA01_201511_201604_SN275/resampled_2kHz/wav"

# fixed path, embeddings will be stored here, advised not to change
# because this is also where bacpipe will look for existing embeddings
main_results_dir :   "results/by_dataset"
embed_parent_dir :   "embeddings"
dim_reduc_parent_dir :   "dim_reduced_embeddings"

# fixed paths for tasks:
task_results_dir : "task_results"
task_config_files : "bacpipe/embedding_evaluation/classification/tasks"


# To avoid creating embeddings when configurations are still being tested, this is set to True. 
# Set to False if you want to keep embeddings even if the process is interrupted.
rm_embedding_on_keyboard_interrupt: True

use_reduced_dim_embeds_for_tasks: True

# supported formats of audio files
audio_suffixes: ['.wav', '.WAV', '.aif', '.mp3', '.flac']

# specify your device ['cpu', 'cuda', ...]
device: 'cpu'

use_parent_dir_as_label: False