name: Explore-GitHub-Actions

on: [push]

jobs:
  explore:
    runs-on: ubuntu-latest
    steps:
      # 1. ADD THIS STEP to clone your repository into the workspace
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. Set up Python (recommended before running pip)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Your custom commands will now work!
      - name: Check requirements file
        run: ls requirements-no-tf.txt

      - name: Install dependencies
        run: pip install -r requirements-no-tf.txt

      - name: Install dependencies
        run: pip install --no-deps -e .

      - name: Run test script
        run: python bacpipe/tests/test_minimal.py
